title: Brandon Patterson
logo: "/images/logo.jpg?raw=true"
description: > 
  Software Engineer with extensive experience in AI research, simulation, and higher education. M.S. in Computer Science with published machine learning research, blending academic innovation with real world applications.
  <br><br>
  Currently exploring data science, deep learning, NLP, and AI driven solutions. Check out my work here.
  <br><br>
  <a href="https://www.linkedin.com/in/brandon-patterson-7038813/">LinkedIn</a> 
  <br>
  <a href="https://orcid.org/0000-0003-2566-6506">ORC ID</a> 
  <br>
  <a href="https://public.tableau.com/profile/brandon2995/">Tableau</a>
  <br>
  <a href="https://www.kaggle.com/mrpantherson/">Kaggle</a>
  <br>
  <a href="https://mrpantherson.pythonanywhere.com/">Flask Playground</a>
  <br>
theme: jekyll-theme-minimal
show_downloads: false
github:
  owner_name: "Brandon"
  is_project_page: true
  is_user_page: false
  repository_url: "https://github.com/mrpantherson/portfolio"
  owner_url: "https://github.com/mrpantherson/"
