title: Brandon Patterson
logo: "/images/logo.jpg?raw=true"
description: > 
  19 year experience as a software engineer in game development, simulation, and education. I have a master's degree in Mobile Software Engineering and have published papers in the field of machine intelligence.
  <br><br>
  Currently fascinated with data science, see more stuff i've done here.
  <br><br>
  <a href="https://www.kaggle.com/mrpantherson/">Kaggle</a>
  <br>
  <a href="https://scholar.google.com/citations?user=zMLTYGAAAAAJ/">Google Scholar</a> 
  <br>
  <a href="https://play.google.com/store/apps/developer?id=Handsome/">Android Play</a> 
  <br>
  <a href="https://public.tableau.com/profile/brandon2995/">Tableau</a>
  
theme: jekyll-theme-minimal
